steps:
  # 1. Create a Docker image containing bigdata-interop repo
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/dataproc-bigdata-interop-presubmit', '-f', 'cloudbuild/Dockerfile', '.']

  # 2. Run Hadoop 2 presumit tests
  - name: 'gcr.io/$PROJECT_ID/dataproc-bigdata-interop-presubmit'
    entrypoint: 'bash'
    args: ['/bigdata-interop/cloudbuild/presubmit.sh', 'hadoop2']

  # 3. Run Hadoop 3 presumit tests
  - name: 'gcr.io/$PROJECT_ID/dataproc-bigdata-interop-presubmit'
    entrypoint: 'bash'
    args: ['/bigdata-interop/cloudbuild/presubmit.sh', 'hadoop3']
