//
// DO NOT EDIT.
// This file is automatically generated from feature-map.json at build time.
//
package com.google.cloud.hadoop.gcsio;

public enum TrackedFeatures {
<% features.eachWithIndex { feature, i -> %>
    ${feature.name}(${feature.bit_position})${ i < features.size() - 1 ? ',' : '' }
<% } %>;

    private final int bitPosition;

    TrackedFeatures(int bitPosition) {
        this.bitPosition = bitPosition;
    }

    public int getBitPosition() {
        return bitPosition;
    }
}
